- .changeset/fifty-rice-explode.md
- .github/workflows/release.yml
- package.json
- packages/client-sdk/package.json
- packages/jsonrpc-engine/package.json
- packages/post-message/package.json
- packages/post-message/src/PostMessageEngine.ts
- packages/post-message/src/index.ts
- Adding some metadata to package.json
- Remove EventMessage since this is not relevant within the post message library.
> Package.json clean up + remove EventMessage

- .changeset/lazy-baboons-appear.md
- .github/workflows/main.yml
- .github/workflows/release.yml
- packages/client-sdk/README.md
- packages/jsonrpc-engine/README.md
- packages/post-message/README.md
> Fix readme typos

- .changeset/lemon-sheep-divide.md
- packages/client-sdk/README.md
- packages/post-message/src/PostMessageEngine.test.ts
- packages/post-message/src/PostMessageEngine.ts
* Originally looked into dropping the window filter which usually is confusing us without adding more security that the origin check doesn't cover (i think, let me know if off there), but moving forward with opt-out instead. More discussion in this [slack thread](https://getmash.slack.com/archives/C028Y700NSE/p1667251908106479)
* Added comments to things
[original slack thread of thinking](https://getmash.slack.com/archives/C028Y700NSE/p1666877270501749)
> Add window filter opt-out and beef up comments

- .changeset/grumpy-keys-decide.md
- packages/post-message/README.md
- packages/post-message/package.json
- packages/post-message/src/PostMessageEngine.ts
- yarn.lock
Add debug messages for why a message is ignored.
> Add debug logs to post message

- .changeset/calm-toes-thank.md
- packages/client-sdk/src/widgets/widgets.ts
- URL for widgets was missing a `/`
> Add missing slash to widgets URL

- .changeset/giant-apricots-try.md
- packages/client-sdk/src/widgets/widgets.ts
Fixing typo in donate button element.
> Fixing donate button typo

- .changeset/stupid-colts-applaud.md
- packages/client-sdk/src/iframe/IFrame.ts
Fixing Ghost and Intercom position bug.
> Fixing Ghost and Intercom position bug

- .changeset/dull-geese-hang.md
- packages/client-sdk/src/Mash.ts
- packages/client-sdk/src/api/routes.ts
- packages/client-sdk/src/widgets/boost.ts
- packages/client-sdk/src/widgets/preconnect.ts
- packages/client-sdk/src/widgets/widgets.ts
* Read boost configurations from API and inject them into the site
* Refactored configuration names to make clear local vs. remote configuration
Closes #47
> Boost configurations

- .changeset/fresh-peas-lie.md
- packages/client-sdk/src/widgets/boost.test.ts
- packages/client-sdk/src/widgets/boost.ts
Was ignoring rules after the first one :blush:
> Fix boost logic

- .changeset/polite-ligers-crash.md
- packages/client-sdk/src/api/routes.ts
- packages/client-sdk/src/iframe/IFrame.test.ts
- packages/client-sdk/src/iframe/IFrame.ts
- packages/client-sdk/src/iframe/position.test.ts
- packages/client-sdk/src/iframe/position.ts
Add client-sdk support for mobile wallet button placement
- Adds wix action bar placement type
- Tested remote config
- Tested manual config
> Add support for mobile wallet button placement

- .changeset/empty-frogs-return.md
- packages/client-sdk/src/Mash.ts
- packages/client-sdk/src/api/routes.ts
- packages/client-sdk/src/widgets/attribute.ts
- packages/client-sdk/src/widgets/boost.ts
- packages/client-sdk/src/widgets/pageMatcher.test.ts
- packages/client-sdk/src/widgets/pageMatcher.ts
- packages/client-sdk/src/widgets/pageRevealer.ts
* Move around shared logic with boost configurations
* Inject page revealers
> Inject page revealer widgets based on earner config

- .changeset/eight-pugs-talk.md
- packages/client-sdk/src/iframe/IFrame.test.ts
- packages/client-sdk/src/iframe/IFrame.ts
Increasing the max size for notifications as needed for the new notification styling.
> increasing Notifications Height

- .changeset/nice-pianos-happen.md
- packages/client-sdk/src/iframe/IFrame.ts
Increasing the size of the Mash Button Iframe
- Closes #1759
> Increasing the size of the Mash Button Iframe

- .changeset/breezy-ravens-love.md
- .changeset/nasty-dancers-whisper.md
- packages/client-sdk/src/Mash.ts
- packages/client-sdk/src/config.test.ts
- packages/client-sdk/src/config.ts
- packages/client-sdk/src/iframe/IFrame.test.ts
- packages/client-sdk/src/iframe/IFrame.ts
- packages/client-sdk/src/iframe/position.ts
- packages/client-sdk/src/index.ts
- packages/client-sdk/src/widgets/boost.ts
Promoted the location of the FAB so other elements (and maybe a general higher order layout function in the future) know where its being placed. Passing it to the boost injection function in order to calculate offsets.
* Added Mash Button settings to local configuration to allow for overrides
> Expose Mash Button position to other elements, configure Boost Buttons based on it

- .changeset/metal-cheetahs-change.md
- packages/client-sdk/src/iframe/IFrame.test.ts
- packages/client-sdk/src/iframe/IFrame.ts
Detect Screen Height and Resize Wallet Accordingly
> Detect Screen Height and Resize Wallet Accordingly

- .changeset/perfect-knives-agree.md
- .github/workflows/test.yml
- packages/client-sdk/src/Mash.ts
- Default placement is now Right instead of Left
- Closes [#1919](https://github.com/getmash/mash/issues/1919)
> Fix default Button App placement to be right instead of left

- .changeset/lovely-pots-prove.md
- README.md
- packages/client-sdk/README.md
- packages/client-sdk/src/config.ts
> Point to app.mash.com

- .changeset/real-students-tease.md
- README.md
- packages/client-sdk/README.md
- packages/client-sdk/src/config.ts
> Get rid of extra .com

- .changeset/heavy-lions-provide.md
- packages/client-sdk/src/Mash.ts
- packages/client-sdk/src/api/routes.test.ts
- packages/client-sdk/src/api/routes.ts
- packages/client-sdk/src/config.ts
- packages/client-sdk/src/iframe/position.ts
- packages/client-sdk/src/index.ts
- Add ability to override remote wallet position configuration through SDK options
- Closes #108 where config wasn't correctly set when an API request failed.
> Add ability to override remote wallet position configuration through SDK options

- .changeset/tough-terms-perform.md
- packages/client-sdk/src/iframe/IFrame.test.ts
- packages/client-sdk/src/iframe/IFrame.ts
- packages/client-sdk/src/iframe/position.ts
- packages/client-sdk/src/widgets/boost.ts
- Remove margins on div and allow Mash widget within the iframe dictate the spacing
- Refactor some of the position code to make it easier to understand what is happening.
> Remove margins wrapping Mash iframe
